<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\PagesController;


Route::get('ecommerce', [DashboardController::class, 'ecommerce'])->name('dashboard.ecommerce');
Route::get('/', [DashboardController::class, 'index'])->name('dashboard.index');
Route::get('projects', [DashboardController::class, 'projects'])->name('dashboard.projects');
Route::get('onlinecourse', [DashboardController::class, 'onlinecourse'])->name('dashboard.onlinecourse');
Route::get('marketing', [DashboardController::class, 'marketing'])->name('dashboard.marketing');
Route::get('overview', [PagesController::class, 'overview'])->name('userprofile.overview');
Route::get('project', [PagesController::class, 'project'])->name('userprofile.project');
Route::get('campaigns', [PagesController::class, 'campaigns'])->name('userprofile.campaigns');
Route::get('documents', [PagesController::class, 'documents'])->name('userprofile.documents');
Route::get('followers', [PagesController::class, 'followers'])->name('userprofile.followers');
Route::get('activity', [PagesController::class, 'activity'])->name('userprofile.activity');
Route::get('overview1', [PagesController::class, 'overview1'])->name('account.overview');
Route::get('settings', [PagesController::class, 'settings'])->name('account.settings');
Route::get('security', [PagesController::class, 'security'])->name('account.security');
Route::get('activity1', [PagesController::class, 'activity1'])->name('account.activity');
Route::get('billing', [PagesController::class, 'billing'])->name('account.billing');
Route::get('statements', [PagesController::class, 'statements'])->name('account.statements');
Route::get('referrals', [PagesController::class, 'referrals'])->name('account.referrals');
Route::get('api', [PagesController::class, 'api'])->name('account.api');
Route::get('logs', [PagesController::class, 'logs'])->name('account.logs');
Route::get('signin', [PagesController::class, 'signin'])->name('corporate-layout.authentication.sign-in');
Route::get('signup', [PagesController::class, 'signup'])->name('corporate-layout.authentication.sign-up');
Route::get('twofactor', [PagesController::class, 'twofactor'])->name('corporate-layout.authentication.two-factor');
Route::get('ResetPassword', [PagesController::class, 'ResetPassword'])->name('corporate-layout.authentication.reset-password');
Route::get('NewPassword', [PagesController::class, 'NewPassword'])->name('corporate-layout.authentication.new-password');
Route::get('signin1', [PagesController::class, 'signin1'])->name('overlay-layout.authentication.sign-in');
Route::get('signup1', [PagesController::class, 'signup1'])->name('overlay-layout.authentication.sign-up');
Route::get('twofactor1', [PagesController::class, 'twofactor1'])->name('overlay-layout.authentication.two-factor');
Route::get('ResetPassword1', [PagesController::class, 'ResetPassword1'])->name('overlay-layout.authentication.reset-password');
Route::get('NewPassword1', [PagesController::class, 'NewPassword1'])->name('overlay-layout.authentication.new-password');
Route::get('signin2', [PagesController::class, 'signin2'])->name('creative-layout.authentication.sign-in');
Route::get('signup2', [PagesController::class, 'signup2'])->name('creative-layout.authentication.sign-up');
Route::get('twofactor2', [PagesController::class, 'twofactor2'])->name('creative-layout.authentication.two-factor');
Route::get('ResetPassword2', [PagesController::class, 'ResetPassword2'])->name('creative-layout.authentication.reset-password');
Route::get('NewPassword2', [PagesController::class, 'NewPassword2'])->name('creative-layout.authentication.new-password');
Route::get('signin3', [PagesController::class, 'signin3'])->name('fancy-layout.authentication.sign-in');
Route::get('signup3', [PagesController::class, 'signup3'])->name('fancy-layout.authentication.sign-up');
Route::get('twofactor3', [PagesController::class, 'twofactor3'])->name('fancy-layout.authentication.two-factor');
Route::get('ResetPassword3', [PagesController::class, 'ResetPassword3'])->name('fancy-layout.authentication.reset-password');
Route::get('NewPassword3', [PagesController::class, 'NewPassword3'])->name('fancy-layout.authentication.new-password');
Route::get('WelcomeMessage', [PagesController::class, 'WelcomeMessage'])->name('email-templates.authentication.welcome-message');
Route::get('ResetPassword4', [PagesController::class, 'ResetPassword4'])->name('email-templates.authentication.reset-password');
Route::get('subscription', [PagesController::class, 'subscription'])->name('email-templates.authentication.subscription-confirmed');
Route::get('card', [PagesController::class, 'card'])->name('email-templates.authentication.card-declined');
Route::get('promo1', [PagesController::class, 'promo1'])->name('email-templates.authentication.promo1');
Route::get('promo2', [PagesController::class, 'promo2'])->name('email-templates.authentication.promo2');
Route::get('promo3', [PagesController::class, 'promo3'])->name('email-templates.authentication.promo3');
Route::get('MultiSteps', [PagesController::class, 'MultiSteps'])->name('authentication.multi-steps-sign-up');
Route::get('welcome', [PagesController::class, 'welcome'])->name('authentication.welcome');
Route::get('VerifyEmail', [PagesController::class, 'VerifyEmail'])->name('authentication.verify-email');
Route::get('ComingSoon', [PagesController::class, 'ComingSoon'])->name('authentication.coming-soon');
Route::get('PasswordConfirmation', [PagesController::class, 'PasswordConfirmation'])->name('authentication.password-confirmation');
Route::get('AccountDeactivated', [PagesController::class, 'AccountDeactivated'])->name('authentication.account-deactivated');
Route::get('error404', [PagesController::class, 'error404'])->name('authentication.error-404');
Route::get('error500', [PagesController::class, 'error500'])->name('authentication.error-500');